# Generated by Django 4.1.3 on 2022-11-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatroom', models.TextField(max_length=10)),
                ('text', models.TextField(max_length=200)),
            ],
        ),
    ]
