# Generated by Django 4.1.3 on 2022-11-25 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('websocket_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='from_user',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
