# Generated by Django 4.1.3 on 2022-11-25 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_app', '0003_remove_chatroom_users_chatroom_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='room_name',
            field=models.TextField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='chatroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websocket_app.chatroom'),
        ),
    ]
