# Generated by Django 4.1.3 on 2023-01-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_app', '0007_alter_message_chatroom_alter_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='name',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
