# Generated by Django 4.1.3 on 2023-01-31 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_app', '0008_chatroom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
