# Generated by Django 4.1.3 on 2023-01-31 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('websocket_app', '0009_message_create'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['create']},
        ),
        migrations.AddField(
            model_name='chatroom',
            name='last_update',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='websocket_app.chatroom')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
