# Generated by Django 4.1.3 on 2023-02-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_app', '0011_alter_chatroom_last_update_alter_chatroom_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
