# Generated by Django 4.1.3 on 2023-02-07 08:44

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default=None, null=True, upload_to=users.models.Profile.user_custom_path),
        ),
    ]
