# Generated by Django 4.1.3 on 2023-02-07 08:45

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default=None, upload_to=users.models.Profile.user_custom_path),
        ),
    ]
